- type: oxydGunConfig
  id: gunConfig
  safetyOn:
    sprite: /Textures/Oxyd/erisported/gunactions16.rsi
    state: safety1
  safetyOff:
    sprite: /Textures/Oxyd/erisported/gunactions16.rsi
    state: safety0
  jammedBallistic:
    path: /Audio/Oxyd/gunjam.ogg
  jammedLaser:
    path: /Audio/Oxyd/gunjam.ogg
