- type: job
  id: MedicalSpecialist
  name: job-name-medspec
  description: job-description-medspec
  playTimeTracker: JobMedicalSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
  startingGear: MedicalSpecialistGear
  icon: "JobIconMedicalSpecialist"
  supervisors: job-supervisors-hos
  access:
  - Security
  - Brig
  - Medical
  - Detective
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MedicalSpecialistGear
  equipment:
    eyes: erisport_Ironhammer_medical_HUD
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
    id: SecurityPDA
  storage:
    back:
    - Flash
    - WeaponPDWMartin
    - MagazinePistol

- type: chameleonOutfit
  id: MedicalSpecialistChameleonOutfit
  job: MedicalSpecialist
  hasMindShield: true
  equipment:
    jumpsuit: erisport_Medical_Specialists_jumpsuit
    outerClothing: erisport_medical_specialists_labcoat
    mask: erisport_Ironhammer_gasmask
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesColorBlack
