using Content.Server._Oxyd.SanityInsightAndResting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.Sanity;

[GenerateTypedNameReferences]
public sealed partial class SanityMenu : Control
{
    private SanityComponent targetComponent;

    public SanityMenu()
    {
        targetComponent = new SanityComponent();
        RobustXamlLoader.Load(this);
    }

    public SanityMenu(SanityComponent cop)
    {
        targetComponent = cop;
        RobustXamlLoader.Load(this);
    }
}

