using Content.Server._Oxyd.SanityInsightAndResting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.Sanity;

[GenerateTypedNameReferences]
public sealed partial class SanityMenu : Control
{
    private SanityComponent targetComponent;

    public SanityMenu()
    {
        targetComponent = new SanityComponent();
        RobustXamlLoader.Load(this);
    }

    public SanityMenu(SanityComponent cop)
    {
        targetComponent = cop;
        RobustXamlLoader.Load(this);
        SanityBar.MinValue = targetComponent.MinSanity;
        SanityBar.MaxValue = targetComponent.MaxSanity;
        SanityBar.Value = targetComponent.Sanity;
        InsightBar.Value =  targetComponent.Insight;
        if (cop.DesireDescription != "")
        {
            DesireText.Text = cop.DesireDescription;
            DesireBar.Value = cop.DesireProgress;
        }
    }

}

