using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.NeoTheology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.NeoTheology.UI;

[GenerateTypedNameReferences]
public sealed partial class ArmamentsPrinterWindow : FancyWindow
{
    private ArmamentsPrinterState? _state;
    private string? _selected;

    public event Action<string>? Purchase;

    public ArmamentsPrinterWindow()
    {
        RobustXamlLoader.Load(this);

        ArmamentList.OnItemSelected += args =>
        {
            _selected = ArmamentList[args.ItemIndex].Metadata as string;
            UpdateDetails();
        };
        ArmamentList.OnItemDeselected += _ =>
        {
            _selected = null;
            UpdateDetails();
        };
        PurchaseButton.OnPressed += _ =>
        {
            if (_selected is { } id)
                Purchase?.Invoke(id);
        };
    }

    public void UpdateState(ArmamentsPrinterState state)
    {
        _state = state;
        ArmamentList.Clear();

        foreach (var entry in state.Entries)
        {
            var item = ArmamentList.AddItem($"{entry.Name} — {entry.Cost}", metadata: entry.Id);
            item.Disabled = !entry.Affordable;
            if (string.Equals(entry.Id, _selected, StringComparison.Ordinal))
                item.Selected = true;
        }

        PointsLabel.Text = Loc.GetString("oxyd-armaments-printer-points",
            ("points", state.Points),
            ("maximum", state.MaxPoints));

        UpdateDetails();
    }

    private void UpdateDetails()
    {
        var entry = _state?.Entries.FirstOrDefault(candidate =>
            string.Equals(candidate.Id, _selected, StringComparison.Ordinal));

        DescriptionLabel.SetMessage(entry?.Description ?? string.Empty);
        StatusLabel.Text = entry is null || entry.Affordable
            ? string.Empty
            : Loc.GetString("oxyd-armaments-printer-too-expensive");
        PurchaseButton.Disabled = entry is null || !entry.Affordable;
    }
}
