using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.NeoTheology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.NeoTheology.UI;

[GenerateTypedNameReferences]
public sealed partial class EyeOfTheProtectorWindow : FancyWindow
{
    public EyeOfTheProtectorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(EyeOfTheProtectorState state)
    {
        ObservationLabel.Text = Loc.GetString("oxyd-eotp-observation", ("observation", (int) state.Observation));
        ArmamentsLabel.Text = Loc.GetString("oxyd-eotp-armaments",
            ("points", state.ArmamentsPoints),
            ("maximum", state.MaxArmamentsPoints));
        MiracleLabel.Text = Loc.GetString("oxyd-eotp-miracle-cooldown", ("cooldown", state.MiracleCooldown.ToString(@"mm\:ss")));
    }
}
