using System.Globalization;
using System.Linq;
using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Shared._Oxyd.NeoTheology;
using Content.Shared._Oxyd.NeoTheology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Oxyd.NeoTheology.UI;

[GenerateTypedNameReferences]
public sealed partial class LitanyWindow : FancyWindow
{
    private const double HolinessTolerance = 0.000001d;
    private const int MaximumPlainTextScalars = 512;
    private const int AllCategoriesId = -1;

    [Dependency] private IGameTiming _gameTiming = default!;

    private LitanyViewerSnapshot? _snapshot;
    private LitanyViewerEntry? _selectedEntry;
    private ProtoId<LitanyPrototype>? _selectedLitany;
    private LitanyCategory? _categoryFilter;
    private LitanyBusyState? _busyState;
    private string? _choiceRequestId;
    private TimeSpan _choiceExpiresAt;
    private List<LitanyChoiceOption> _choiceOptions = new();
    private string? _resultText;
    private uint _resultRevision;
    private bool _hasRolePresentation;
    private bool _hasCruciform;

    public event Action<ProtoId<LitanyPrototype>, uint, string?>? BeginLitany;
    public event Action<string, List<string>, NeoTheologySpecialization?, string?, string?>? SubmitChoices;
    public event Action<string>? CancelLitany;

    public LitanyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CategorySelector.Prefix = "Category:";
        SpecializationSelector.Prefix = "Specialization:";

        SearchBar.OnTextChanged += _ => RefreshEntryList(preserveSelection: false);
        CategorySelector.OnItemSelected += args =>
        {
            _categoryFilter = args.Id == AllCategoriesId
                ? null
                : (LitanyCategory?) (args.Id - 1);
            RefreshEntryList(preserveSelection: false);
        };

        BeginButton.OnPressed += _ => BeginSelectedLitany();
        SubmitChoiceButton.OnPressed += _ => SubmitPendingChoices();
        CancelButton.OnPressed += _ => CancelPendingRequest();

        ChoiceList.OnItemSelected += _ => UpdateChoiceControls();
        ChoiceList.OnItemDeselected += _ => UpdateChoiceControls();

        PlainTextEdit.IsValid = IsPlainTextLengthValid;
        PlainTextEdit.OnTextChanged += _ => UpdatePlainTextCount();

        foreach (var specialization in Enum.GetValues<NeoTheologySpecialization>())
        {
            SpecializationSelector.AddItem(specialization.ToString(), (int) specialization);
        }

        UpdatePlainTextCount();
    }

    /// <summary>
    /// Supports the original BUI state path while servers migrate to the
    /// actor-targeted snapshot message. The state contains no actor or entity
    /// identity, and the server remains authoritative for every decision.
    /// </summary>
    public void UpdateState(LitanyViewerSnapshot snapshot)
    {
        if (_snapshot is not null && snapshot.Revision < _snapshot.Revision)
            return;

        _hasRolePresentation = false;
        var catalogChanged = _snapshot is null || CatalogChanged(_snapshot.Entries, snapshot.Entries);
        _snapshot = snapshot;

        if (catalogChanged)
            RefreshCategories();

        UpdateProfilePresentation();
        RefreshEntryList(preserveSelection: true);
        UpdateBusyPresentation();
    }

    /// <summary>
    /// Applies the private viewer snapshot sent as a BUI message. Only this
    /// viewer's role, resource values and entry availability are rendered.
    /// </summary>
    public void UpdateSnapshot(LitanyViewerSnapshotMessage snapshot)
    {
        if (_snapshot is not null && snapshot.Revision < _snapshot.Revision)
            return;

        _busyState = snapshot.BusyState;

        var role = snapshot.RolePresentation;
        UpdateState(new LitanyViewerSnapshot(
            snapshot.Revision,
            snapshot.Holiness,
            snapshot.MaximumHoliness,
            snapshot.RegenerationPerSecond,
            role.Rank,
            role.Specialization,
            role.Clearance,
            role.Active,
            snapshot.Entries,
            null));

        // UpdateState also supports the legacy state path and clears this
        // marker, so apply the actor-targeted role presentation after it runs.
        _hasRolePresentation = true;
        _hasCruciform = role.HasCruciform;
        UpdateProfilePresentation();

        if (_busyState is null)
            ClearChoiceSnapshot();
        else if (!string.Equals(_choiceRequestId, _busyState.RequestId, StringComparison.Ordinal))
            ClearChoiceSnapshot();

        UpdateBusyPresentation();
    }

    /// <summary>
    /// Displays the server-authored choice labels and stores only their opaque
    /// tokens in ItemList metadata. Labels are rendered as plain text and are
    /// never resolved into entities or identifiers on the client.
    /// </summary>
    public void UpdateChoiceSnapshot(LitanyChoiceSnapshotMessage snapshot)
    {
        if (_snapshot is not null && snapshot.Revision < _snapshot.Revision)
            return;

        if (_busyState is not null && !string.Equals(_busyState.RequestId, snapshot.RequestId, StringComparison.Ordinal))
            return;

        var requestChanged = !string.Equals(_choiceRequestId, snapshot.RequestId, StringComparison.Ordinal);
        var selectedTokens = requestChanged
            ? new HashSet<string>(StringComparer.Ordinal)
            : ChoiceList.GetSelected()
                .Select(item => item.Metadata)
                .OfType<string>()
                .ToHashSet(StringComparer.Ordinal);

        _choiceRequestId = snapshot.RequestId;
        _choiceExpiresAt = snapshot.ExpiresAt;
        _choiceOptions = snapshot.AllowedChoices;
        RebuildChoiceList(selectedTokens);
        UpdateChoiceControls();
    }

    /// <summary>
    /// Updates the local progress presentation from server timestamps. No
    /// client-side effect or completion is inferred from this message.
    /// </summary>
    public void UpdateProgress(LitanyProgressMessage progress)
    {
        if (_snapshot is not null && progress.Revision < _snapshot.Revision)
            return;
        if (_busyState is not null && !string.Equals(_busyState.RequestId, progress.RequestId, StringComparison.Ordinal))
            return;

        _busyState = new LitanyBusyState(
            progress.RequestId,
            progress.Litany,
            progress.Stage,
            progress.StartedAt,
            progress.EndsAt,
            progress.CanCancel);
        UpdateBusyPresentation();
    }

    /// <summary>
    /// Shows the server-provided result. A result for an older request cannot
    /// clear a newer busy or choice state.
    /// </summary>
    public void UpdateResult(LitanyResultMessage result)
    {
        if (_snapshot is not null && result.Revision < _snapshot.Revision)
            return;

        _resultRevision = result.Revision;
        _resultText = result.Success
            ? Loc.GetString("oxyd-litany-success")
            : result.Reason is { } reason
                ? Loc.GetString("oxyd-litany-failed", ("reason", Loc.GetString(reason)))
                : Loc.GetString("oxyd-litany-failed", ("reason", "Unknown reason"));

        if (result.RequestId is { } requestId &&
            (string.Equals(requestId, _busyState?.RequestId, StringComparison.Ordinal)
             || string.Equals(requestId, _choiceRequestId, StringComparison.Ordinal)))
        {
            _busyState = null;
            ClearChoiceSnapshot();
        }

        UpdateBusyPresentation();
    }

    public override void Close()
    {
        // Closing is deliberately not cancellation. The explicit Cancel button
        // is the only client action that emits CancelLitany.
        base.Close();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateProgressPresentation();
    }

    /// <summary>
    /// Sends cancellation only for the current server-issued request and only
    /// when the server marked that request cancellable.
    /// </summary>
    public void CancelPendingRequest()
    {
        var requestId = _busyState is { CanCancel: true } busy
            ? busy.RequestId
            : _choiceRequestId;
        if (requestId is null)
            return;

        CancelLitany?.Invoke(requestId);
        _busyState = null;
        ClearChoiceSnapshot();
        UpdateBusyPresentation();
    }

    private void RefreshCategories()
    {
        CategorySelector.Clear();
        CategorySelector.AddItem("All", AllCategoriesId);

        if (_snapshot is null)
            return;

        foreach (var category in _snapshot.Entries
                     .Select(entry => entry.Category)
                     .Distinct()
                     .OrderBy(category => (int) category))
        {
            CategorySelector.AddItem(category.ToString(), (int) category + 1);
        }

        if (_categoryFilter is { } filter && !CategorySelector.TrySelectId((int) filter + 1))
            _categoryFilter = null;
        else if (_categoryFilter is null)
            CategorySelector.TrySelectId(AllCategoriesId);
    }

    private void RefreshEntryList(bool preserveSelection)
    {
        if (_snapshot is null)
            return;

        var scrollValue = EntryScroll.GetScrollValue();
        var filteredEntries = GetFilteredEntries().ToList();
        LitanyViewerEntry? entryToSelect = null;

        if (preserveSelection && _selectedLitany is { } selectedId)
        {
            entryToSelect = _snapshot.Entries.FirstOrDefault(entry => entry.Litany.Equals(selectedId));
        }

        if (!preserveSelection || entryToSelect is null && _selectedLitany is null)
            entryToSelect = filteredEntries.FirstOrDefault();

        if (!preserveSelection && entryToSelect is null)
            _selectedLitany = null;

        EntryList.DisposeAllChildren();
        EmptyCatalogLabel.Visible = filteredEntries.Count == 0;

        var buttonGroup = new ButtonGroup();
        foreach (var entry in filteredEntries)
        {
            var name = Loc.GetString(entry.Name);
            var suffix = entry.Available ? string.Empty : " [Unavailable]";
            var button = new Button
            {
                Text = $"{entry.Category}: {name}{suffix}",
                HorizontalExpand = true,
                MinHeight = 30,
                ToggleMode = true,
                Group = buttonGroup,
                Pressed = entryToSelect is not null && entry.Litany.Equals(entryToSelect.Litany),
                ToolTip = Loc.GetString(entry.Description),
                StyleClasses = { "ButtonSquare" },
            };

            button.OnPressed += _ => SelectEntry(entry);
            EntryList.AddChild(button);
        }

        if (entryToSelect is null)
        {
            _selectedEntry = null;
            UpdateDetails();
        }
        else
        {
            SelectEntry(entryToSelect, refreshList: false);
        }

        EntryScroll.SetScrollValue(scrollValue);
    }

    private IEnumerable<LitanyViewerEntry> GetFilteredEntries()
    {
        if (_snapshot is null)
            return Enumerable.Empty<LitanyViewerEntry>();

        var search = SearchBar.Text.Trim();
        return _snapshot.Entries
            .Where(entry => _categoryFilter is null || entry.Category == _categoryFilter)
            .Where(entry => string.IsNullOrEmpty(search)
                            || Loc.GetString(entry.Name).Contains(search, StringComparison.CurrentCultureIgnoreCase)
                            || Loc.GetString(entry.Description).Contains(search, StringComparison.CurrentCultureIgnoreCase))
            .OrderBy(entry => (int) entry.Category)
            .ThenBy(entry => Loc.GetString(entry.Name), StringComparer.CurrentCultureIgnoreCase)
            .ThenBy(entry => entry.Litany.ToString(), StringComparer.Ordinal);
    }

    private void SelectEntry(LitanyViewerEntry entry, bool refreshList = true)
    {
        _selectedLitany = entry.Litany;
        _selectedEntry = entry;
        UpdateDetails();

        if (refreshList)
            RefreshEntryList(preserveSelection: true);
    }

    private void UpdateProfilePresentation()
    {
        if (_snapshot is not { } snapshot)
            return;

        HolinessLabel.Text = Loc.GetString("oxyd-cruciform-holiness",
            ("current", snapshot.Holiness.ToString("0.##")),
            ("maximum", snapshot.MaximumHoliness.ToString("0.##")));
        RegenerationLabel.Text = $"Regeneration: {snapshot.RegenerationPerSecond.ToString("0.####", CultureInfo.CurrentCulture)}/s";

        var hasCruciform = _hasRolePresentation
            ? _hasCruciform
            : snapshot.Active || snapshot.MaximumHoliness > 0;
        RankLabel.Text = Loc.GetString("oxyd-cruciform-rank",
            ("rank", hasCruciform ? snapshot.Rank.ToString() : "—"));
        SpecializationLabel.Text = Loc.GetString("oxyd-cruciform-specialization",
            ("specialization", hasCruciform ? snapshot.Specialization.ToString() : "—"));
        ClearanceLabel.Text = Loc.GetString("oxyd-cruciform-clearance",
            ("clearance", hasCruciform ? snapshot.Clearance.ToString() : "—"));

        HolinessBar.MaxValue = snapshot.MaximumHoliness > 0 && double.IsFinite(snapshot.MaximumHoliness)
            ? (float) Math.Min(snapshot.MaximumHoliness, float.MaxValue)
            : 1f;
        HolinessBar.Value = double.IsFinite(snapshot.Holiness)
            ? (float) Math.Clamp(snapshot.Holiness, 0d, Math.Max(1d, snapshot.MaximumHoliness))
            : 0f;
    }

    private void UpdateDetails()
    {
        if (_selectedEntry is not { } entry)
        {
            SelectedName.Text = "Select a litany";
            SelectedDescription.SetMessage(string.Empty);
            PhraseLabel.Text = string.Empty;
            CostLabel.Text = string.Empty;
            CooldownLabel.Text = string.Empty;
            CastDurationLabel.Text = string.Empty;
            TargetLabel.Text = string.Empty;
            AvailabilityLabel.Text = string.Empty;
            BeginButton.Disabled = true;
            UpdateChoiceControls();
            return;
        }

        SelectedName.Text = Loc.GetString(entry.Name);
        SelectedDescription.SetMessage(Loc.GetString(entry.Description));
        PhraseLabel.Text = $"Phrase: {entry.Phrase}";
        CostLabel.Text = Loc.GetString("oxyd-litany-ui-cost", ("cost", entry.Cost.ToString("0.##")));
        CooldownLabel.Text = Loc.GetString("oxyd-litany-ui-cooldown", ("duration", FormatDuration(entry.Cooldown)));
        CastDurationLabel.Text = $"Cast duration: {FormatDuration(entry.CastDuration)}";
        TargetLabel.Text = $"Target mode: {entry.TargetMode}";

        if (entry.Available)
        {
            AvailabilityLabel.Text = "Available";
        }
        else
        {
            var reason = entry.UnavailableReason is { } reasonId
                ? Loc.GetString(reasonId)
                : "This litany is not available to the viewer.";
            AvailabilityLabel.Text = Loc.GetString("oxyd-litany-ui-unavailable", ("reason", reason));
        }

        UpdateChoiceControls();
    }

    private void UpdateChoiceControls()
    {
        var requiresChoice = _selectedEntry is { } entry && RequiresChoice(entry);
        var hasChoiceRequest = _choiceRequestId is not null;
        var choosing = hasChoiceRequest && (_busyState is null || _busyState.Stage == LitanyCastStage.Choosing);

        ChoiceContainer.Visible = requiresChoice || hasChoiceRequest;
        ChoiceInstructionLabel.Text = hasChoiceRequest
            ? "Select one or more server-provided choices."
            : requiresChoice
                ? "The server will provide eligible choices after Begin."
                : string.Empty;
        ChoiceList.Visible = hasChoiceRequest && _choiceOptions.Count > 0;
        ChoiceExpiryLabel.Visible = hasChoiceRequest;
        SpecializationRow.Visible = hasChoiceRequest;
        RecipeRow.Visible = hasChoiceRequest;
        PlainTextRow.Visible = hasChoiceRequest;
        PlainTextCountLabel.Visible = hasChoiceRequest;
        PendingRequestLabel.Visible = hasChoiceRequest;

        SubmitChoiceButton.Visible = hasChoiceRequest;
        SubmitChoiceButton.Disabled = !hasChoiceRequest || !choosing || ChoiceExpired();
        CancelButton.Visible = _busyState is not null || hasChoiceRequest;
        CancelButton.Disabled = _busyState is not { CanCancel: true } && !hasChoiceRequest;

        if (hasChoiceRequest)
        {
            ChoiceExpiryLabel.Text = $"Choice expires at: {_choiceExpiresAt.TotalSeconds:0.##} s";
            PendingRequestLabel.Text = "Server request is active; its ID remains opaque.";
        }
        else
        {
            ChoiceExpiryLabel.Text = string.Empty;
            PendingRequestLabel.Text = string.Empty;
        }

        BeginButton.Disabled = !CanBeginSelectedLitany();
    }

    private void RebuildChoiceList(HashSet<string>? selectedTokens = null)
    {
        selectedTokens ??= ChoiceList.GetSelected()
            .Select(item => item.Metadata)
            .OfType<string>()
            .ToHashSet(StringComparer.Ordinal);

        ChoiceList.Clear();
        foreach (var option in _choiceOptions)
        {
            // DisplayLabel is server-authored plain text. Token is retained only
            // as opaque metadata and is never shown or resolved by the client.
            var item = ChoiceList.AddItem(option.DisplayLabel, metadata: option.Token);
            if (selectedTokens.Contains(option.Token))
                item.Selected = true;
        }
    }

    private void BeginSelectedLitany()
    {
        if (_snapshot is null || _selectedEntry is not { } entry || !CanBeginSelectedLitany())
            return;

        // Initial target selection is server-driven. The optional token in the
        // message remains null until a future server contract supplies one.
        BeginLitany?.Invoke(entry.Litany, _snapshot.Revision, null);
    }

    private void SubmitPendingChoices()
    {
        if (_choiceRequestId is not { } requestId || ChoiceExpired())
            return;

        var tokens = ChoiceList.GetSelected()
            .Select(item => item.Metadata as string)
            .Where(token => token is not null)
            .Cast<string>()
            .ToList();
        var specialization = SpecializationSelector.SelectedId == (int) NeoTheologySpecialization.None
            ? null
            : (NeoTheologySpecialization?) SpecializationSelector.SelectedId;
        var recipeId = string.IsNullOrEmpty(RecipeIdEdit.Text) ? null : RecipeIdEdit.Text;
        var plainText = string.IsNullOrEmpty(PlainTextEdit.Text) ? null : PlainTextEdit.Text;

        SubmitChoices?.Invoke(requestId, tokens, specialization, recipeId, plainText);
    }

    private void ClearChoiceSnapshot()
    {
        _choiceRequestId = null;
        _choiceExpiresAt = default;
        _choiceOptions = new List<LitanyChoiceOption>();
        ChoiceList.Clear();
        SpecializationSelector.TrySelectId((int) NeoTheologySpecialization.None);
        RecipeIdEdit.Clear();
        PlainTextEdit.Clear();
    }

    private void UpdateBusyPresentation()
    {
        UpdateProgressPresentation();
        UpdateChoiceControls();

        if (_snapshot is null)
            return;

        if (_busyState is not null)
        {
            StatusLabel.Text = $"{_busyState.Stage}: {_busyState.Litany}";
            return;
        }

        if (_resultText is not null && _resultRevision >= _snapshot.Revision)
        {
            StatusLabel.Text = _resultText;
            return;
        }

        var hasCruciform = _hasRolePresentation
            ? _hasCruciform
            : _snapshot.Active || _snapshot.MaximumHoliness > 0;
        StatusLabel.Text = _snapshot.BusyReason ?? (_snapshot.Active
            ? string.Empty
            : hasCruciform
                ? Loc.GetString("oxyd-cruciform-inactive")
                : Loc.GetString("oxyd-cruciform-no-implant"));
    }

    private void UpdateProgressPresentation()
    {
        if (_busyState is not { } busy)
        {
            CastProgressBar.Visible = false;
            CastProgressLabel.Text = string.Empty;
            return;
        }

        var duration = busy.EndsAt - busy.StartedAt;
        var fraction = duration <= TimeSpan.Zero
            ? 1f
            : (float) ((_gameTiming.CurTime - busy.StartedAt).TotalSeconds / duration.TotalSeconds);
        CastProgressBar.Visible = true;
        CastProgressBar.Value = Math.Clamp(fraction, 0f, 1f);
        var remaining = busy.EndsAt - _gameTiming.CurTime;
        CastProgressLabel.Text = remaining > TimeSpan.Zero
            ? $"{busy.Stage}: {FormatDuration(remaining)} remaining"
            : $"{busy.Stage}: completing";
    }

    private bool CanBeginSelectedLitany()
    {
        if (_snapshot is not { Active: true } snapshot || _selectedEntry is not { } entry)
            return false;
        if (!entry.Available
            || _busyState is not null
            || _choiceRequestId is not null
            || !string.IsNullOrWhiteSpace(snapshot.BusyReason))
            return false;
        if (!double.IsFinite(snapshot.Holiness) || !double.IsFinite(entry.Cost) || entry.Cost < 0)
            return false;

        return snapshot.Holiness + HolinessTolerance >= entry.Cost;
    }

    private bool ChoiceExpired()
    {
        return _choiceRequestId is not null && _gameTiming.CurTime >= _choiceExpiresAt;
    }

    private static bool RequiresChoice(LitanyViewerEntry entry)
    {
        return entry.TargetMode is not LitanyTargetMode.Self
            and not LitanyTargetMode.None;
    }

    private static bool CatalogChanged(List<LitanyViewerEntry> oldEntries, List<LitanyViewerEntry> newEntries)
    {
        if (oldEntries.Count != newEntries.Count)
            return true;

        foreach (var current in newEntries)
        {
            var previous = oldEntries.FirstOrDefault(entry => entry.Litany.Equals(current.Litany));
            if (previous is null || !EntryEqual(previous, current))
                return true;
        }

        return false;
    }

    private static bool EntryEqual(LitanyViewerEntry left, LitanyViewerEntry right)
    {
        return left.Category == right.Category
               && left.Name.Equals(right.Name)
               && left.Description.Equals(right.Description)
               && left.Phrase == right.Phrase
               && left.Cost.Equals(right.Cost)
               && left.Cooldown == right.Cooldown
               && left.CastDuration == right.CastDuration
               && left.TargetMode == right.TargetMode
               && left.Available == right.Available
               && left.UnavailableReason.Equals(right.UnavailableReason);
    }

    private void UpdatePlainTextCount()
    {
        var count = CountUnicodeScalars(PlainTextEdit.Text);
        PlainTextCountLabel.Text = $"Message length: {count}/{MaximumPlainTextScalars} Unicode scalars";
    }

    private static bool IsPlainTextLengthValid(string value)
    {
        return CountUnicodeScalars(value) <= MaximumPlainTextScalars;
    }

    private static int CountUnicodeScalars(string value)
    {
        return value.EnumerateRunes().Count();
    }

    private static string FormatDuration(TimeSpan duration)
    {
        if (duration <= TimeSpan.Zero)
            return "none";
        if (duration.TotalHours >= 1)
            return $"{duration.TotalHours:0.##} h";
        if (duration.TotalMinutes >= 1)
            return $"{duration.TotalMinutes:0.##} min";
        return $"{duration.TotalSeconds:0.##} s";
    }
}
