using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Oxyd.Skills.UI;

[GenerateTypedNameReferences]
public sealed partial class SkillMenu : Control
{
    public SkillMenu()
    {
        RobustXamlLoader.Load(this);
    }
}

