- type: oxydNeoTheologyProfile
  id: OxydNtDisciple
  name: oxyd-neotheology-profile-disciple
  accessPrivileges:
  - OxydNtFollower
  cruciformCapacity: 50
  regenerationMultiplier: 1
  litanySets:
  - OxydLitanyCommon
  - OxydLitanyMachinery
  canChannel: false
  countsAsChannelingFollower: true

- type: oxydNeoTheologyProfile
  id: OxydNtAcolyte
  name: oxyd-neotheology-profile-acolyte
  accessPrivileges:
  - OxydNtFollower
  - OxydNtCommon
  cruciformCapacity: 50
  regenerationMultiplier: 1
  litanySets:
  - OxydLitanyCommon
  - OxydLitanyMachinery
  - OxydLitanyAcolyte
  canChannel: false
  countsAsChannelingFollower: true

- type: oxydNeoTheologyProfile
  id: OxydNtAgrolyte
  name: oxyd-neotheology-profile-agrolyte
  accessPrivileges:
  - OxydNtFollower
  - OxydNtCommon
  cruciformCapacity: 50
  regenerationMultiplier: 1
  litanySets:
  - OxydLitanyCommon
  - OxydLitanyMachinery
  - OxydLitanyAgrolyte
  canChannel: false
  countsAsChannelingFollower: true

- type: oxydNeoTheologyProfile
  id: OxydNtCustodian
  name: oxyd-neotheology-profile-custodian
  accessPrivileges:
  - OxydNtFollower
  - OxydNtCommon
  cruciformCapacity: 50
  regenerationMultiplier: 1
  litanySets:
  - OxydLitanyCommon
  - OxydLitanyMachinery
  - OxydLitanyCustodian
  canChannel: false
  countsAsChannelingFollower: true

- type: oxydNeoTheologyProfile
  id: OxydNtPreacher
  name: oxyd-neotheology-profile-preacher
  accessPrivileges:
  - OxydNtFollower
  - OxydNtCommon
  cruciformCapacity: 80
  regenerationMultiplier: 1.15
  litanySets:
  - OxydLitanyCommon
  - OxydLitanyMachinery
  - OxydLitanyAcolyte
  - OxydLitanyPriest
  canChannel: true
  countsAsChannelingFollower: false

- type: oxydNeoTheologyProfile
  id: OxydNtInquisitor
  name: oxyd-neotheology-profile-inquisitor
  accessPrivileges:
  - OxydNtFollower
  - OxydNtCommon
  - OxydNtClergy
  cruciformCapacity: 100
  regenerationMultiplier: 1.25
  litanySets:
  - OxydLitanyCommon
  - OxydLitanyMachinery
  - OxydLitanyAcolyte
  - OxydLitanyPriest
  - OxydLitanyInquisitor
  canChannel: true
  countsAsChannelingFollower: false
